# Generated by Django 4.2.4 on 2023-08-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prod',
            old_name='seales',
            new_name='seales_name',
        ),
    ]
