# Generated by Django 4.2.4 on 2023-08-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_seales_prod_seales_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='buy_options',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prod',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
