# Generated by Django 4.2.4 on 2023-08-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_prod_buy_options_prod_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='buy_options',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white')], default='chose one', max_length=15),
        ),
    ]
