# Generated by Django 4.2.4 on 2023-08-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_prod_buy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='buy_options',
            field=models.CharField(choices=[('black', '100$'), ('white', '150$')], max_length=15),
        ),
    ]
