# Generated by Django 4.2.4 on 2023-08-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_prod_buy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='buy_options',
            field=models.CharField(choices=[('100$', 'black'), ('150$', 'white')], max_length=15),
        ),
    ]
